### ISSUE TITLE
Anyoneplaying command

### ISSUE THREAD

**Issue by invicta-nz** [makupi/pavlov-bot#10]
New command ;anyoneplaying that loops through all configured servers issuing ServerInfo and RefreshList command

Allow anyone to issue this command

**Comment by invicta-nz** [comment]
I am thinking now an optional  line in servers.json for anyoneplaying:group. So calling ;anyoneplaying apac will get my servers (tagged as such)

**Comment by invicta-nz** [comment]
;anyoneplaying breaks when loading info from this incompletely populated steam page:
https://steamcommunity.com/sharedfiles/filedetails/?id=2111731598


```
Jun 25 09:47:41 Pavlov-syd pipenv[377]: 2020-06-25 09:47:41,809 root         INFO     9101 - RCON _recv data='{\n\t"ServerInfo":\n\t{\n\t\t"MapLabel": "UGC2111731598",\n\t\t"GameMode": "SND",\n\t\t"ServerName": "[ArcticVR][NA-WEST]Summer SND1",\n\t\t"RoundState": "Started",\n\t\t"PlayerCount": "0/10"\n\t}\n}\r\n'
Jun 25 09:47:42 Pavlov-syd pipenv[377]: 2020-06-25 09:47:42,721 root         ERROR    Getting map label failed with list index out of range
```

Looks like when it gets this error, it stops looping and exits. Likely a ``won't fix`` sort of error for right now as it is likely edge case and map dev will resolve by adding image to project.

**Comment by makupi** [comment]
Ah okay, I'll still add some error handling to catch the issue.

**Comment by makupi** [comment]
Closing this through #42 - Filtering will be done through #39
