### ISSUE TITLE
Configuable Admin level

### ISSUE THREAD

**Issue by oneSALTycracker** [makupi/pavlov-bot#125]
so on our servers i dont mind if an admin uses the ;giveitem cmd  so we have to add there discord ids .. but now i have put in ;command to turn off/on/restart the servers id like that to be limited to only a fue but with the way the bot is now i cannot without removing the ;giveitem it would really be great if there where a way as a user to config the cmds each level can use or maybe even add a third one 

thank you

**Comment by invicta-nz** [comment]
Unfortunately with how the bot is written it is not possible for end users to configure command permission levels. If you want to get a bit hacky you can move the block of code that drives `;giveitem` from bot/cogs/pavlov_admin.py to /bot/cogs/pavlov_mod.py to change the permission level of this command.
