### ISSUE TITLE
I just have a question about the status

### ISSUE THREAD

**Issue by Josephfallen** [makupi/pavlov-bot#143]
So I want to change the status from ![image](https://user-images.githubusercontent.com/108951296/190399002-3cb930ac-bcff-4dc2-971f-a1c6b954d5ec.png) (item circled) how would I change that. (I.E. where is the code that sets this)

**Comment by makupi** [comment]
@Josephfallen https://github.com/makupi/pavlov-bot/blob/master/bot/__init__.py#L42 You can change the text here instead of the `f"v{__version__}"` just put `"Hello World!"`
