### ISSUE TITLE
help command has gotten too long and makes discord unhappy.

### ISSUE THREAD

**Issue by invicta-nz** [makupi/pavlov-bot#43]
Adding 4 new commands to help has broken it by hitting a discord character/line limit. Fixed temp by removing help from fairly useless Maplist command. At some point need to look into ways of fixing. Perhaps breaking help into Admin-only commands and the rest.

**Comment by makupi** [comment]
Temporarily fixed in b9d397bd1c3dc7aa8bf7b42c3b181e381ea8a0a2 
- if characters exceed 1024 splits into new field. Should work for a while but will work on a refactor soon.
