### ISSUE TITLE
Pavlov Bot to embed mesage to Discord Channel given certain events such as player count

### ISSUE THREAD

**Issue by frostyboskitzo** [makupi/pavlov-bot#57]
### fanboy gush
This FR is not related to a problem. @psimyn and I are Aussie Pavlov VR enthusiasts, and I found your bot and am running it on my dedicated server and it's been a lifesaver for getting fast downloads for custom maps from the workshop on crappy aussie internet connections - also longer times for custom maps that need it. I digress, but just wanted to thank you for putting this out there.

## stories
As a user, I would like to know when there are people in the server. I know that I can execute a command `;serverinfo server_name` but if I don't have the permission for that, or if I'm not sitting there refreshing it, it's tedious to know when the boys have jammed on the HMDs and are getting ready for some cheeky TTT.

As an administrator, I don't want to have to run `;serverinfo` commands to check when folks are in the server - I'd like Discordbot to message me, or @me in the channel that it operates in.

As a user, I'd like to exist in a role (outside of scope of this feature, auto role assignment exists in another bot) which can then get tagged by Pavlov bot when players are in the server.

As a user, I don't want to get tagged all the time - so many just when the server reaches a predefined number of players: perhaps a variable which can be set administratively so that when `X` number of players are in the server, pavlov-bot @'s the channel / role, and then won't @ anyone again until that resets to 0.

# Description of the possible solution

In config.json a series of values:
`allow discord role alert` (default value 0, enabled as 1, must be integer)
`discord alert role name` (no default, must be set without the "@" - for example a rolename of 'pavlovplayers', must be string)
`discord alert server list` (if not set, all servers, if set, only listed server names separated by comma, must be string)
`minimum players alert trigger` (default to 1, unless otherwise set, must be integer)
`discord alert message` (default to something lame, but can be changed to include text plus variables? unsure if possible in JSON.)

If the allow alert is set to 0, all alert functions are disabled.

If set to 1, the role name must be set in config and exist on the discord server, and presumably have permissions in the channel that pavlov-bot lives in (or pavlov-bot to have that role? I'm fuzzy on discord roles/perms)

`alert server list` should default to all servers; if defined, uses the function to get server.

The feature then listens to the servers and, when the player count goes from `0` to `minimum_players_alert_trigger` or greater, pavlov-bot then embeds a discord message to target all the roles - something like "@pavlovplayers, server_name is booming! server_name.players are already online - get in on the action".
Alternatively, a custom discord alert message, and optionally/possibly the embed of the player numbers and server_name.

**Describe alternatives you've considered**
I am not good enough at python to make something like this myself. There doesn't appear to be a function that's similar to what I want that I can adapt that code and create a pseudocode version, even, so I wouldn't really know where to begin. No other bot can listen to the servers, and this one already has that facillity because of RCON, so it makes sense that Pavlov-bot is the one to do the needful.

**Additional context**
N/A

**Comment by invicta-nz** [comment]
The main issue here is that this would be the first change to the bot that makes it go from being a passive command interpreter to making a loop of constant queries to the server that the result of which would trigger actions. Another previous enhancement that we haven't followed up on (#17) would also do this, and I would suggest that any architecture to handle one of these two enhancements be generalised to potential handle both.

**Comment by invicta-nz** [comment]
@frostyboskitzo In case it seems makupi is a bit unresponsive to feature requests, understand that this was a bit of a lockdown project for both of us, but also that I hired him to create the code I wanted (at very reasonable rates) as a bit of a side project for him. Lockdown is over for us and the bot has matured to something pretty stable, so our engagement has reduced. That said, if you really want a feature request implemented and you are willing to paypal some $$ his way, interest in that feature might become much more focused. :)

**Comment by makupi** [comment]
It does sound like an interesting feature, that might be useful for other people as well.     
The configuration could look something like this:
```jsonc
{
    "prefix": ";",
    "token": "token",
    "discordAlert": {
        "enabled": true, // default = disabled
        "severs": [
            "rush"
        ], // list of servers, default = all
        "guildId": 123445676788, // server id where it should be posted, required.
        "channelId": 23242342342, // channel id where it should be posted, required.
        "playerThreshold": 10, // amount of players to trigger alert, default = 1
        "message": "@pavlovplayers, {server_name} is booming! {player_count} are already online - get in on the action!"
    }
}
```

Pretty sure channel and guild Id would be necessary to find the channel, the mention of the role should most likely be possible directly in the message, as long as the role name exists. 

Code wise, this would probably just be a `task` that is executed about every minute and looks through all servers. This task could be combined with #17 or other features like this as well.

**Comment by invicta-nz** [comment]
Yeah, I could see this being useful for smaller discords that don't have standard play times. Would be nice to have a general task system in place as well. 

BTW @frostyboskitzo you and your crew should stop by the APAC Pavlov discord if you haven't already (https://discord.gg/4wcBSMU).

**Comment by frostyboskitzo** [comment]
Thanks for the info, Invicta, and the invite. I'd definitely be keen to splash a bit of cash @makupi's way - like I said, I can read/edit most code, but I'm terrible at writing new functions in languages that I don't know well. Ruby and PHP are my "best" languages and that's tentative.

Regarding a running task, does Python have anything similar to "sidekiq" for ruby which can schedule tasks, and execute them? A framework like that should take out a lot of the heavy lifting and we can just pass it parameters.

The example of the config was pretty much exactly what I was thinking. I should have JSONified it for you, I'm sorry.

I'm not sure how 'developery' you want to get on this, should I raise a separate issue to work on a "task" system to support #57 and #17 ? I don't mind, I live in Gitlab at work anyway what's one more issue :)

**Comment by invicta-nz** [comment]
I am pretty relaxed, but I have never been a serious dev, but sounds like you know github best practices better then I. THB, this is my first serious use if git beyond just downloading/fetching code as a sysadmin and it has been a great learning experience. Since we all seem agreed that a generalised task system is the way to go, might as well open up an issue for that.
