### ISSUE TITLE
Ban for all servers

### ISSUE THREAD

**Issue by Ne-Row** [makupi/pavlov-bot#68]
If someone has multiple servers, would it make sense to have the ;ban function add the banned STEAMID to all servers? I feel that if you have reason to ban someone and have multiple servers, I want that person banned on all my servers. if you typed ";ban 700000000000000000" it should ban for all, but if you wanted to ban only for one server for whatever reason, you could use the current command ";ban 700000000000000000 < servername >"

just a thought!

**Comment by invicta-nz** [comment]
If all of your servers are on the same host this is easily accomplished by having one lead blacklist.txt file and the rest of the instances are symlinks to this file. Ban on one, automatic ban on all. But still not a bad idea for a ;globalban command.

**Comment by makupi** [comment]
Good idea. Could also just make the server-name in the ;ban optional and if not given automatically ban on all servers? What do you think @invicta-nz?
Currently ;ban is defaulting to the default-server, could instead just default to "all"

**Comment by invicta-nz** [comment]
Yeah, that could work. Only reason I hesitated is that it would be a bit different from other commands (in applying to all instead of default). But as long as you can still ban on explicitly one server in case that is what you need then it shouldn't be too confusing.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by oneSALTycracker** [comment]
we started using a symbolic link for the blacklist like invicta recommended to me ages ago and it works great 

something like this 

```
ln -s /home/steam/linked/blacklist.txt /home/steam/pavlovserver0/Pavlov/Saved/Config/blacklist.txt

ln -s /home/steam/linked/blacklist.txt /home/steam/pavlovserver1/Pavlov/Saved/Config/blacklist.txt
 
```
 it took a wile to figure out but then it just makes a copy of the list sent to all servers and if ur banned in 1 ur banned in all

**Comment by oneSALTycracker** [comment]
yea sorry i deleted my original msg because i realized u had to have a reason for wanting them separate  i swear i remember reading about using vpn (the real ones not nord) to trick the servers to thinking them they are on the same network but im sure that is far more than its worth 

but for context lol

**Comment by frostyboskitzo** [comment]
The bot writes to a main blacklist file as text. You could have your Pavlov servers on different machines pull this text via a separate script on a Cron? Host the file, which is regularly updated by pavlovbot behind Http-basic authentication and a 
Cron Using wget will solve your problem in the short term.

**Comment by Ne-Row** [comment]
That was a lot of smart words…I don’t think I have the brains to implement what you just suggested but now I’m going to try to look into it! Thanks!

Solomon Nero
Nero Minded Productions
(518)698-6263 
nero-minded.com

**Comment by oneSALTycracker** [comment]
hey so in trying t find a fix to my feature request i think i stumbled onto something that might help you too 

so my problem was i wanted to limit the ; command to only some admins so the fix i found was to just have a second bot that runs the cmds then it sends the ;commands and i can remove them from the main bot but if theres a way to pass the argument {STEAMID} to the command u could use a netcat script to send bans down to all the servers maybe... im just not sure how to send the {STEAMID} to the netcat script but its an idea

**Comment by invicta-nz** [comment]
That's a pretty amazing workaround, but luckily `;ban {id} all` has already been implemented in the RC build.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by oneSALTycracker** [comment]
hey i thing i found a easy fix for this 
make a repository with the blacklist.txt 
git clone the repo somewhere on the server the make a symbolic link to the correct place and make a cronjob to just git pull every night to update it 

i think this will work
