### ISSUE TITLE
Map, playername and team aliases via config file

### ISSUE THREAD

**Issue by invicta-nz** [makupi/pavlov-bot#7]
As you have likely noticed maps and players are horribly represented by strings of numbers. Want to make this more human friendly with an alias lookup table for each. This could be a static .json file to start with, with the idea of moving towards dynamic editing of this file ";addmap alias UGC### mirage" When a command was called it would check if it is numeric format, if not then check alias table, otherwise fail. Goal is to get something that instead of typing ;switchmap UGC2342355435 SND beta you could have ;switchmap mirage SND beta or ;player perc

Team aliases will be needed for feature request Team vs Team

**Comment by invicta-nz** [comment]
After recent update to get real map name from steam. Can we add a field to serverinfo of mapalias when one is defined. Will give hint to user of an alias if defined, but won't override the real name

**Comment by makupi** [comment]
`aliases.json` format:
```json
{
  "maps": {
    "rush": "UGC123123",
  },
  "players": {
    "player-name": 123123123
  },
  "teams": {
    "team a": [123123, 12312312, 123123]
  }
}
```

**Comment by makupi** [comment]
Should team aliases accept player alliases as parameters? @invicta-nz

**Comment by invicta-nz** [comment]
Hmm.. good question. Seems handy, but also the source of issues if player alias is later removed or you enter a bad name. If easy to do and can cover those potential errors, then would be cool. But if it is getting a bit recursive, then shouldn't be a problem to leave as steamIDs

**Comment by makupi** [comment]
I would've thought of parsing the whole teams on startup to have only steam-id teams in RAM. So in case there is an error with one of the aliases inside the team I could throw an error right away.

**Comment by invicta-nz** [comment]
As discussed, let's stick w/ SteamIDs for simplicity and robustness in future
