### ISSUE TITLE
Add flush command

### ISSUE THREAD

**Issue by invicta-nz** [makupi/pavlov-bot#71]
Would like to add a ";flush server" command that will do the following:

- Grab the list of players on a server and put playerIDs into an list
- Compare that list of playerIDs to player list in aliases.json and remove any that exist in the aliases file
- Randomly choose a player from remaining list and kick them from the server. 

Goal is to have a public server, but players with bot access can kick a unknown player to make space for a registered one. 

@makupi If you are interested in taking this on along with a bit of cleanup of some of the suggested dependency updates, we can restart our previous arraignment. Hope things are going well for you.

**Comment by makupi** [comment]
@invicta-nz Sounds good, I might have some time this weekend. I'll hit you up on discord later!

**Comment by invicta-nz** [comment]
Good question is who is allowed to flush... lets start with this being an anyone command. Might have to move it to captain if abused.
